Unified the name of Request parameters across the file
vapor/api-template pull request #37
Opened 2017-07-12 20:37 UTC by Cellane

All other methods have the Request parameter called `req` instead of `request`, thus I propose changing it from `request` to `req` for the `create` method as well.

2017-07-19 18:56 UTC, tanner0101 requested changes

2017-07-19 18:56 UTC, tanner0101 commented on Sources/App/Controllers/PostController.swift
> +    func create(req: Request) throws -> ResponseRepresentable {
Using `_ req: Request` here would be preferred. `Request` is strongly typed so we don't need to be redundant with the parameter label.

2017-07-20 12:45 UTC, Cellane commented
Like this? I removed the labels from all the methods in the file and adjusted tests accordingly.

2017-07-20 18:21 UTC, tanner0101 approved these changes

2017-07-20 18:21 UTC, tanner0101 commented
Thanks :)

2017-07-20 18:21 UTC, merged